"""empty message

Revision ID: 2650f946d2b8
Revises: c355beee93d1
Create Date: 2022-01-20 14:28:02.119487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2650f946d2b8'
down_revision = 'c355beee93d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('heading', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'heading')
    # ### end Alembic commands ###
