"""empty message

Revision ID: 65c69bdcd080
Revises: 9f3a0016679a
Create Date: 2022-01-19 10:42:17.829540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65c69bdcd080'
down_revision = '9f3a0016679a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('contentImage', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'contentImage')
    # ### end Alembic commands ###
